name: Build and Sign Artifact

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # Required for OIDC keyless signing
  contents: read

jobs:
  build-sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build artifact
      run: |
        echo "Hello Rakesha 🚀" > artifact.txt
        tar -czf artifact.tar.gz artifact.txt

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign artifact with OIDC
      run: |
        cosign sign-blob \
          --yes \
          --output-signature artifact.sig \
          --output-certificate artifact.pem \
          artifact.tar.gz

    - name: Verify signature
      run: |
        cosign verify-blob \
          --signature artifact.sig \
          --certificate artifact.pem \
          --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/sign-artifact.yml@refs/heads/main" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          artifact.tar.gz

    - name: Upload signed files
      uses: actions/upload-artifact@v4
      with:
        name: signed-artifact
        path: |
          artifact.tar.gz
          artifact.sig
          artifact.pem
